"""Storage contract shared by checkpoint writers and readers."""

CHECKPOINT_OBJECTS_DIR = "objects"
CHECKPOINT_SCHEMA_VERSION = 27
CHECKPOINT_POLICY_FILENAME = "policy.pt"
CHECKPOINT_TRAINER_FILENAME = "trainer.pt"

__all__ = (
    "CHECKPOINT_OBJECTS_DIR",
    "CHECKPOINT_SCHEMA_VERSION",
    "CHECKPOINT_POLICY_FILENAME",
    "CHECKPOINT_TRAINER_FILENAME",
)
