// Generated by scripts/generate_training_dashboard_contracts.py.
// Do not edit by hand.

export const TRAINING_EVENT_SCHEMA_VERSION = 5 as const;
export const TRAINING_METRICS_SCHEMA_VERSION = 6 as const;
export const TRAINING_EVENT_NAMES = [
  "initialize",
  "training",
  "process.start",
  "process.stop",
  "sampling",
  "round",
  "update",
  "update.rank",
  "checkpoint",
  "inference.batch",
  "logging.drop",
] as const;
export const TRAINING_PROCESS_KINDS = [
  "initializer",
  "coordinator",
  "worker",
  "model_rank",
] as const;
