"""Generate the frontend view of current training wire contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic import TypeAdapter

from server.foundation.json_value import JsonObject
from server.training_events import (
    EVENT_NAMES,
    PROCESS_KINDS,
    TRAINING_EVENT_SCHEMA_VERSION,
    TrainingEvent,
    TrainingEventContext,
    TrainingEventProcess,
    TrainingLogHistoryPage,
    TrainingLogRecord,
)
from server.training_metrics import (
    TRAINING_METRICS_SCHEMA_VERSION,
    MetricDatasets,
    MetricPoint,
    TrainingMetrics,
)

_ROOT = Path(__file__).parents[1]
_GENERATED_TYPESCRIPT = (
    _ROOT
    / "frontend"
    / "training-dashboard"
    / "contracts"
    / "generated.ts"
)
_GENERATED_FIXTURE = (
    _ROOT
    / "frontend"
    / "training-dashboard"
    / "tests"
    / "fixtures"
    / "generated-contract.json"
)
_JSON_OBJECT_ADAPTER: TypeAdapter[JsonObject] = TypeAdapter(JsonObject)


def generated_artifacts() -> tuple[tuple[Path, str], ...]:
    """Return every path and its exact generated current content."""
    return (
        (_GENERATED_TYPESCRIPT, _typescript_contract()),
        (_GENERATED_FIXTURE, _json_contract_fixture()),
    )


def _typescript_contract() -> str:
    return (
        "// Generated by "
        "scripts/generate_training_dashboard_contracts.py.\n"
        "// Do not edit by hand.\n\n"
        "export const TRAINING_EVENT_SCHEMA_VERSION = "
        f"{TRAINING_EVENT_SCHEMA_VERSION} as const;\n"
        "export const TRAINING_METRICS_SCHEMA_VERSION = "
        f"{TRAINING_METRICS_SCHEMA_VERSION} as const;\n"
        "export const TRAINING_EVENT_NAMES = "
        f"{_typescript_string_tuple(EVENT_NAMES)}"
        "export const TRAINING_PROCESS_KINDS = "
        f"{_typescript_string_tuple(PROCESS_KINDS)}"
    )


def _typescript_string_tuple(values: tuple[str, ...]) -> str:
    items = "".join(
        f"  {json.dumps(value, ensure_ascii=False)},\n"
        for value in values
    )
    return f"[\n{items}] as const;\n"


def _json_contract_fixture() -> str:
    fixture: JsonObject = {
        "training_log_page": _json_object(
            _training_log_page().model_dump_json()
        ),
        "training_metrics": _json_object(
            _training_metrics().model_dump_json()
        ),
    }
    return (
        json.dumps(
            fixture,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n"
    )


def _training_log_page() -> TrainingLogHistoryPage:
    event = TrainingEvent(
        schema_version=TRAINING_EVENT_SCHEMA_VERSION,
        event="update",
        recorded_at_ms=1234,
        process=TrainingEventProcess(
            kind="coordinator",
            index=0,
            pid=17,
        ),
        context=TrainingEventContext(
            policy_version=3,
            rollout_id="rollout-current",
            worker_index=1,
            model_rank_index=2,
            game_env_index=3,
            episode_id=4,
            seat="a",
            decision_index=5,
            request_id=6,
            batch_id=7,
        ),
        fields={
            "policy_loss": 0.25,
            "objective_loss": 0.2,
        },
    )
    failed = TrainingEvent(
        schema_version=TRAINING_EVENT_SCHEMA_VERSION,
        event="checkpoint",
        recorded_at_ms=1235,
        process=TrainingEventProcess(
            kind="coordinator",
            index=None,
            pid=17,
        ),
        context=TrainingEventContext(),
        fields={},
        error="checkpoint rejected",
    )
    return TrainingLogHistoryPage(
        store_id="0123456789abcdef0123456789abcdef",
        events=(
            TrainingLogRecord(sequence=8, event=event),
            TrainingLogRecord(sequence=9, event=failed),
        ),
        next_before_sequence=None,
    )


def _training_metrics() -> TrainingMetrics:
    point = MetricPoint(
        sequence=9,
        update=3,
        elapsed_seconds=1.5,
        recorded_at_ms=1235,
        values={"objective_loss": 0.2},
    )
    return TrainingMetrics(
        schema_version=TRAINING_METRICS_SCHEMA_VERSION,
        store_id="0123456789abcdef0123456789abcdef",
        through_sequence=9,
        complete=True,
        dropped_event_count=0,
        totals={"total_updates": 3},
        datasets=MetricDatasets(
            throughput=(point,),
            optimization=(point,),
            ppo_timing=(point,),
            rollout=(point,),
            rewards=(point,),
            inference=(point,),
            processes=(point,),
        ),
    )


def _json_object(text: str) -> JsonObject:
    return _JSON_OBJECT_ADAPTER.validate_json(text)


def _write_artifacts() -> int:
    try:
        for path, content in generated_artifacts():
            path.parent.mkdir(parents=True, exist_ok=True)
            _ = path.write_text(content, encoding="utf-8")
    except OSError as error:
        print(f"contract generation failed: {error}", file=sys.stderr)
        return 1
    return 0


def _check_artifacts() -> int:
    for path, expected in generated_artifacts():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            print(
                f"generated contract is missing: {path}",
                file=sys.stderr,
            )
            return 1
        if actual != expected:
            print(
                f"generated contract is stale: {path}", file=sys.stderr
            )
            return 1
    return 0


def main(arguments: tuple[str, ...]) -> int:
    """Write or verify the checked-in current contract artifacts."""
    if arguments == ("--write",):
        return _write_artifacts()
    if arguments == ("--check",):
        return _check_artifacts()
    print(
        "usage: python -m "
        + "scripts.generate_training_dashboard_contracts "
        + "--write|--check"
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main(tuple(sys.argv[1:])))
