"""Semantic argument sequences generated by the training policy."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from server.result import Ok, Rejected
from server.rules.card_faces import (
    CardFace,
    FaceCount,
    face_sort_key,
)

type SemanticArgumentKind = Literal["pass", "stop", "select_face_count"]


@dataclass(frozen=True, slots=True)
class SemanticArgumentPrefix:
    """Current generated semantic argument prefix."""

    arguments: tuple[SemanticArgument, ...]


@dataclass(frozen=True, slots=True)
class SemanticArgument:
    """One incremental semantic action argument."""

    kind: SemanticArgumentKind
    face_count: FaceCount | None = None


@dataclass(frozen=True, slots=True)
class SemanticArgumentTrace:
    """Full generated semantic argument trace for one action."""

    arguments: tuple[SemanticArgument, ...]


class InvalidSemanticActionRejected(Rejected):
    """Semantic action sequence violated the model grammar."""

    def __init__(self, reason: str) -> None:
        super().__init__(f"语义动作非法：{reason}")


def semantic_prefix_state(
    prefix: SemanticArgumentPrefix,
) -> Ok[tuple[FaceCount, ...]] | Rejected:
    """Return selected face counts after applying a prefix."""
    selected: list[FaceCount] = []
    terminated = False
    for argument in prefix.arguments:
        if terminated:
            return InvalidSemanticActionRejected(
                "终止参数后还有额外参数"
            )
        if argument.kind in ("pass", "stop"):
            terminated = True
            continue
        if argument.face_count is None:
            return InvalidSemanticActionRejected(
                "select_face_count 缺少牌面"
            )
        if _face_already_selected(
            tuple(selected), argument.face_count.face
        ):
            return InvalidSemanticActionRejected("同一牌面重复选择")
        if selected and face_sort_key(argument.face_count.face) <= (
            face_sort_key(selected[-1].face)
        ):
            return InvalidSemanticActionRejected("牌面未按规范顺序选择")
        selected.append(argument.face_count)
    return Ok(value=tuple(selected))


def _face_already_selected(
    selected: tuple[FaceCount, ...],
    face: CardFace,
) -> bool:
    return any(item.face == face for item in selected)
